language: cpp

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: gcc
      dist: trusty
    - os: osx
      compiler: clang
      osx_image: xcode6.4
    - os: osx
      compiler: clang
      osx_image: xcode7.3
    - os: osx
      compiler: clang
      osx_image: xcode8
    - os: osx
      compiler: clang
      osx_image: xcode8.1
    - os: osx
      compiler: clang
      osx_image: xcode8.2

addons:
  apt:
    packages:
    - libpcap-dev
    - net-tools

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure-mac_os_x.sh      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure-linux.sh --default; fi
  - make all
  
script:
  - cd Tests/Packet++Test
  - Bin/Packet++Test
  - cd ../Pcap++Test
  - sudo Bin/Pcap++Test -n
  - cd ../..
  - bash Deploy/deploy-travis.sh
